name: Automated testing

on: [push]

jobs:
  call-testing-workflow:
    uses: digitalutsc/reusable_workflows/.github/workflows/ci-testing.yml@main
    with:
      module_name: media_thumbnails_tiff
      composer_name: drupal/media_thumbnails_tiff
      test_suite: null
