name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://git.drupalcode.org/project/media_thumbnails_tiff"
      env:
        GITLAB_HOSTNAME: "git.drupal.org"
        GITLAB_USERNAME: "project_113252_bot"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "113252"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
